server:
       port: 8080
       context-path: /SpringBoot
cupSize: F
age: 18
content: "cup size is ${cupSize}, age is ${age}"

logging:
 config: classpath:log4j2-prod.xml

boy:
    sex : male
    hobby: football